### ISSUE TITLE
Can't paste into tm-switcher on Windows

### ISSUE THREAD

**Issue by johnholbrook** [brenapp/tm-switcher#38]
I'm not able to paste text into the tm-switcher terminal emulator on Windows. 

Pasting into tm-switcher is desirable because both the TM API and the OBS Websocket integration generate long random passwords/keys by default and offer to copy them to the clipboard. Without being able to paste into the tm-switcher window, it's necessary to manually transcribe a long random string (prone to errors) or change the password/API key to something more easily type-able (which is my current solution, but less secure, and an additional step when configuring TM).

I verified this behavior on the most recent version (currently 1.9.0) on Windows 10.

**Comment by brenapp** [comment]
Interesting! I would imagine this is dependent on the terminal emulator you have set as the default. i.e. if you have Windows Terminal set as the default, it should work as expected. 

Can you use Shift+Ins, which I think is the default for `cmd.exe`, the default terminal host?

Because Operating Systems are generally less amenable to allowing people to just ship raw binaries to end users, I am wanting to move this project in a direction where we ship a terminal emulator (xterm.js) as a single application bundle for our supported platforms. Or hell, it may be easier to just write a User Interface, with it.
